[workspace]
resolver = "2"
members = [
    "crates/crabstash",
    "crates/crabstash-common",
    "crates/crabstash-lock",
    "crates/crabstash-storage",
    "crates/crabstash-txn",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92.0"
license = "MIT"
repository = "https://github.com/danpasecinic/crabstash"

[workspace.dependencies]
crabstash = { path = "crates/crabstash" }
crabstash-common = { path = "crates/crabstash-common" }
crabstash-storage = { path = "crates/crabstash-storage" }
crabstash-lock = { path = "crates/crabstash-lock" }
crabstash-txn = { path = "crates/crabstash-txn" }

bytes = "1.11.0"
dashmap = "6.1.0"
crossbeam-skiplist = "0.1.3"
crossbeam-channel = "0.5.15"
parking_lot = "0.12.5"
crc32fast = "1.5.0"
eyre = "0.6.12"
lz4_flex = "0.12.0"
moka = { version = "0.12.12", features = ["sync"] }
wide = "1.1.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
