[workspace]
resolver = "2"
members = [
    "crates/crabstash",
    "crates/crabstash-common",
    "crates/crabstash-storage",
    "crates/crabstash-txn",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92.0"
license = "MIT"
repository = "https://github.com/danpasecinic/crabstash"

[workspace.dependencies]
crabstash = { path = "crates/crabstash" }
crabstash-common = { path = "crates/crabstash-common" }
crabstash-storage = { path = "crates/crabstash-storage" }
crabstash-txn = { path = "crates/crabstash-txn" }

bytes = "1.9"
crossbeam-skiplist = "0.1"
parking_lot = "0.12"
crc32fast = "1.4"
eyre = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
